### PR TITLE
keep game state - require localstorage dependency

### PR DESCRIPTION
**Pull request by luarjm**
Hello!,

I hace added recently the feature to keep the game state in local storage.
Pros: keep the game state i think is very usful for play in diferent times.
Cons:You require the localStorage dependency.

Thanks a lot, I'm enjoying creating my own adventure for android and ios.

### CODE REVIEW

**Comment by danielstern** [comment]
Thanks!

I'll just assume this all works and we can always revert it if it doesn't

**Comment by luarjm** [comment]
Hello,

It works but *you need the localStorage dependency.*

I would create a new brach for it istead of merge in  master brach.

Thanks!

**Comment by danielstern** [comment]
Good call. Reverted, feel free to create a branch for this, if you need Admin privileges let me know

**Comment by luarjm** [comment]
Hello!,

I can't create a new branch

**Pull request merged**
